# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: health.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'health.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0chealth.proto\x12\x06health\"x\n\nHealthData\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12\x18\n\x10\x62ody_temperature\x18\x03 \x01(\x02\x12\x12\n\nheart_rate\x18\x04 \x01(\x05\x12\x16\n\x0e\x62lood_pressure\x18\x05 \x01(\t\"\x1a\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\t2G\n\rHealthService\x12\x36\n\x0eSendHealthData\x12\x12.health.HealthData\x1a\x10.health.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'health_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHDATA']._serialized_start=24
  _globals['_HEALTHDATA']._serialized_end=144
  _globals['_RESPONSE']._serialized_start=146
  _globals['_RESPONSE']._serialized_end=172
  _globals['_HEALTHSERVICE']._serialized_start=174
  _globals['_HEALTHSERVICE']._serialized_end=245
# @@protoc_insertion_point(module_scope)
